### ISSUE TITLE
TypeError: [...] unexpected keyword argument 'send_aggressively'

### ISSUE THREAD

**Issue by mvarendorff** [SOBotics/Botpy#27]
Trying to run [Thunder](https://github.com/SOBotics/Thunder) I got this traceback:

```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    Thunder("geisterfurz007", email, password, rooms=[167908])
  File "main.py", line 23, in __init__
    self.bot = bp.Bot(name, all_commands, rooms, [], "stackoverflow.com", email, password)
  File "/home/redacted-user/.local/lib/python3.7/site-packages/BotpySE/Bot.py", line 28, in __init__
    super().__init__(host, email, password, send_aggressively=send_aggressively)
TypeError: __init__() got an unexpected keyword argument 'send_aggressively'
Exception ignored in: <function Client.__del__ at 0x7f5e3cfc5378>
Traceback (most recent call last):
  File "/home/redacted-user/.local/lib/python3.7/site-packages/chatexchange/client.py", line 165, in __del__
    if self.logged_in:
AttributeError: 'Bot' object has no attribute 'logged_in'
```

This is probably (likely?) related to #17?

**Comment by tripleee** [comment]
https://pypi.org/project/BotpySE/ is now 0.7.8
